### ISSUE TITLE
DX conversion fails

### ISSUE THREAD

**Issue by orbeckst** [Becksteinlab/BornProfiler#10]
Creating DX files for PMF grids fails because BP did not keep up with GridDataFormats. 

Code needs to be changed to work with latest GDF.

Reported by @ChenouZhang

**Comment by orbeckst** [comment]
Commit https://github.com/Becksteinlab/BornProfiler/pull/11/commits/10194190ff080cb6aa8ab05441a3d2adcb871032  in PR #11 solves this problem. @ChenouZhang if you make a separate PR with the fix I'll merge it right away.

**Comment by ChenouZhang** [comment]
PR #13 fixes this problem.
