### ISSUE TITLE
use KDE for creating the PMF

### ISSUE THREAD

**Issue by orbeckst** [Becksteinlab/BornProfiler#12]
The current approach to use a weighted histogram to build the PMF on a grid can lead to 3D PMFs that are patchy. Instead we should just use a KDE to estimate the density from the compute points and then sample the KDE on an arbitrary resolution grid to write a DX file.

* [scipy Gaussian KDE](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.gaussian_kde.html)

**Comment by ChenouZhang** [comment]
Scipy KDE currently has problems handling with Boltzmann distributed  probabilities (ranged from 10e-200 to 1) and created artificial patterns with a 3D PMF data. We decided to switch back to hist method with spline interpolation. The hist method worked just fine.
